In [3]:
import numpy as np
print(np.__version__)

2.3.1


In [5]:
arr_1 = np.array([10,20,30,40])
print(arr_1)
print(type(arr_1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
arr_2 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2)
print(type(arr_2))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [14]:
lst = [10,20,30,40]
print(lst * 2)
print(type(lst))

num_arr = np.array([11,22,33,44,55])
print(num_arr * 2)
print(type(num_arr))

[10, 20, 30, 40, 10, 20, 30, 40]
<class 'list'>
[ 22  44  66  88 110]
<class 'numpy.ndarray'>


In [20]:
vector = np.array([10,20,30, 40])
print("Vector \n", vector)

matrix = np.array([
    [1,2,3], 
    [4,5,6],
    [7,8,9]])
print("Matrix: \n", matrix)

Vector 
 [10 20 30 40]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(matrix.shape)
print(matrix.dtype)
print(matrix.size)
print(matrix.ndim)


(3, 3)
int64
9
2


In [49]:
arr = np.arange(20)
print(arr)

reshaped = arr.reshape((5, 4))
print("Reshaped array: \n", reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [50]:
flat = reshaped.flatten()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [56]:
sarvam = np.array([
 [ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]
])
# print(sarvam)

san = sarvam.flatten()
print(san)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [58]:
rav = sarvam.ravel()
print(rav)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [62]:
sarvam[2, 3] = 100
print(sarvam)

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]
 [ 12  13  14  15]
 [ 16  17  18  19]]


In [63]:
print(sarvam)

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]
 [ 12  13  14  15]
 [ 16  17  18  19]]
