In [2]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
# print(arr[2:7])
print(arr[1:9:2])
print(arr[-3])

[2 4 6 8]
8


In [14]:
unsorted = np.array([1,8,4,7,3,9,2,0,5,6])
print(np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [2, 1], [4, 1]])
# print(np.sort(arr_2d_unsorted, axis = 0))
print(np.sort(arr_2d_unsorted, axis = 1))

[0 1 2 3 4 5 6 7 8 9]
[[1 3]
 [1 2]
 [1 4]]


In [17]:
even_number = unsorted[unsorted % 2 == 0]
print(even_number)

[8 4 2 0 6]


In [18]:
mask = unsorted > 5
print(unsorted[mask])

[8 7 9 6]
